name: hospital_stay_helper
description: A project help patient navigate hospitay and avoid unexpected medical bill.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Flutter localization
  flutter_localizations:
    sdk: flutter
  focused_menu: 
  shared_preferences: 
  cupertino_icons: 
  geolocator:
  dropdown_search:
  reorderables: 
  url_launcher:
  http:
  intro_slider: 
  material_floating_search_bar: 
  flutter_screenutil:
  expandable:
  csv:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/data/usStates.json
    - assets/data/proceduresList.csv
    - locales/EN.json
    - locales/ES.json
    - locales/KR.json
    - locales/VI.json

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400