name: hospital_stay_helper
description: A project help patient navigate hospitay and avoid unexpected medical bill.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Flutter localization
  flutter_localizations:
    sdk: flutter
  intl:
  shared_preferences: 2.0.6
  cupertino_icons:
  geolocator: 7.0.3
  dropdown_search: 0.6.1
  reorderables: 0.4.1
  hexcolor: 2.0.3
  url_launcher: 6.0.6
  http: 0.13.3
  material_floating_search_bar: 0.3.4
  flutter_screenutil: 5.0.0+2
  expandable: 5.0.1
  csv: 5.0.0
  badges: 2.0.1
  flutter_svg: 0.22.0
  image_picker: ^0.8.0+3 
  path_provider: ^2.0.2
  path: ^1.8.0
  percent_indicator: "^2.1.7+2"
  drop_cap_text: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0

flutter_native_splash:
  color: "#FDEBF1"
  image: assets/splash_512.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    # - assets/data/usStates.json
    # - assets/data/proceduresList.csv
    - assets/data/provider.json
    - assets/images/
    - locales/EN.json
    - locales/ES.json
    - locales/KR.json
    - locales/VI.json

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
